server:
  port: 8080

spring:
  application:
    name: spring-boot-tutorial
#  datasource:
#    driverClassName: org.postgresql.Driver
#    url: jdbc:postgresql://127.0.0.1:5432/tvseries?stringtype=unspecified&ApplicationName=tutorial
#    username: pgdbo
#    password: sql
  jackson:
    serialization:
      write-dates-as-timestamps: true  #使用数值timestamp表示日期

  #定义静态资源文件输出路径
  mvc:
    static-path-pattern: /nodeFile/**
  resources:
    static-locations: file:target/uploadFileCache/**, file:target/uploadFileCache/static/, file:target/uploadFileCache/interact/, file:target/uploadFileCache/viewerCache/


  #Define the max request size for file upload
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

mybatis.configuration.mapUnderscoreToCamelCase: true

logging:
  file: target/app.log
  level:
    ROOT: WARN
    cn.Boy: TRACE
    cn.Boy.DiskFile.dao: WARN

#此项目的自定义属性  
DiskFile:
  streamFileCacheFolder: target/uploadFileCache    #文件上传目录，可以用/开头的绝对路径
  viewerCacheFileFolder: target/uploadFileCache/viewerCache

  datasource:
    className:  com.mysql.jdbc.jdbc2.optional.MysqlDataSource #postgresql org.postgresql.ds.PGSimpleDataSource  #使用HikariDataSource的配置
    serverName: localhost # #remote:localhost/192.168.125.129  local:127.0.0.1
    portNumber: 3306       #5432
    dataBaseName: board_diskFile        #main_db
    user: root #pgdbo
    password: whoisboy #sql #remote: Whoisboy!2018 local:whoisboy
    maxPoolSize: 15
  cephCluster:
    apiUrl: http://192.168.125.130:5000/api/v0.1/
    username: admin
    userKey: AQDyuF1dpxsnExAAAIkIlT3m7gcuhgvW+aPmiw==
    monIpStr: 192.168.125.128:6789;192.168.125.129:6789;192.168.125.130:6789
    mountPath: /


platformArch:
#定义DISKFILE微服务集群IP
  CrystalClusterIps: 192.168.125.129;192.168.125.130
#定义搜索优化配置参数
  PoSeidong:
    RulePersistentScanRate: 10
    MemoryLiveTimeSec: 100
    MemoryPerHitComeUpSeconds: 15
#定义Virtual CDN
  ViewerFileCache:
    defaultViewerCacheLength: 3
    ViewerFileCacheRevokeRate: 10
    ViewerFileNameHashTimes: 3
    ViewerCacheFileNameLenth: 32
    ViewerFileCachePullRate: 5
#定义平台交互残留文件的"垃圾"回收频率
  LocalNotExistFileClearRate: 10


